required_fields:
  - scientificName
  - recordedBy
  - eventDate

patterns:
  scientificName: '^[A-Z][a-z]+ [a-z]+$'
  recordedBy: '^Collected by: (?P<recordedBy>.+)$'
  eventDate: '^Date: (?P<eventDate>\\d{4}-\\d{2}-\\d{2})$'
